//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concesionario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoExistencia
    {
        public int IdAutoExistencia { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> IdAutos { get; set; }
        public Nullable<int> IdModelo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdSucursal { get; set; }
    
        public virtual Autos Autos { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
