//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concesionario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraDePago
    {
        public int id_Bitacora { get; set; }
        public Nullable<System.DateTime> FechaDePago { get; set; }
        public Nullable<decimal> Abono { get; set; }
        public Nullable<decimal> PagoMinimo { get; set; }
        public Nullable<int> IdVentaAuto { get; set; }
        public Nullable<decimal> Restante { get; set; }
    
        public virtual VentaAuto VentaAuto { get; set; }
    }
}
