//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concesionario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.DatosFinanciamiento = new HashSet<DatosFinanciamiento>();
            this.VentaAuto = new HashSet<VentaAuto>();
            this.VentaParte = new HashSet<VentaParte>();
        }
    
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public string ApP { get; set; }
        public string ApM { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<System.DateTime> FechaDeNacimiento { get; set; }
        public Nullable<int> Sexo { get; set; }
        public string RFC { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> CP { get; set; }
        public string Telefono { get; set; }
        public string TelefonoCasa { get; set; }
        public string Correo { get; set; }
        public Nullable<int> IdAval { get; set; }
    
        public virtual Aval Aval { get; set; }
        public virtual Sexo Sexo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatosFinanciamiento> DatosFinanciamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaAuto> VentaAuto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaParte> VentaParte { get; set; }
    }
}
