//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concesionario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosFinanciamiento
    {
        public int IdDatosFinanciamiento { get; set; }
        public string NombreEnTC { get; set; }
        public string NoTarjetaC { get; set; }
        public Nullable<int> IdMesExpiracion { get; set; }
        public Nullable<int> IdFechaExpiracion { get; set; }
        public string CVV { get; set; }
        public Nullable<int> CPFacturacion { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<decimal> PrimerPago { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdTiempoDePago { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual FechaExpiracion FechaExpiracion { get; set; }
        public virtual MesExpiracion MesExpiracion { get; set; }
        public virtual TiempoDePago TiempoDePago { get; set; }
    }
}
