//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concesionario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartesPrecioBitacora
    {
        public int IdPartesPrecioBitacora { get; set; }
        public int IdPartes { get; set; }
        public int IdPartesPrecio { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Partes Partes { get; set; }
        public virtual PartesPrecio PartesPrecio { get; set; }
    }
}
