//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concesionario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartesInventario
    {
        public int IdPartesInventario { get; set; }
        public Nullable<int> IdPartes { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> IdSucursal { get; set; }
    
        public virtual Partes Partes { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
