//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concesionario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaAuto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VentaAuto()
        {
            this.BitacoraDePago = new HashSet<BitacoraDePago>();
        }
    
        public int IdVentaAuto { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public int IdAutos { get; set; }
        public int IdAuto_Adic { get; set; }
        public int IdCliente { get; set; }
        public int IdSucursal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdVendido { get; set; }
    
        public virtual Auto_Adiccionales Auto_Adiccionales { get; set; }
        public virtual Autos Autos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraDePago> BitacoraDePago { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Vendido Vendido { get; set; }
    }
}
